In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("data.csv")

In [3]:
def normalize(x):
    mean = x.mean()
    std = x.std()
    return (x  - mean)/std

In [4]:
x = np.array(data.iloc[:,1])
y = np.array(data.iloc[:,2])
z = np.array(data.iloc[:,3])
out = np.array(data.iloc[:,4])

In [5]:
x

array([ 2, 82, 10,  1, 86, 36, 15, 40, 38, 29, 64, 39, 55, 50, 85, 93,  6,
        9, 44, 30, 78, 21,  2, 96, 72, 49, 88, 97, 59, 37, 99, 30, 15, 56,
       93, 21, 43, 89, 39, 57, 28, 54, 38, 36, 11,  9,  9, 19, 34, 10, 94,
       96, 69, 31, 97, 46, 51,  9, 55, 55, 83,  2, 12, 97, 13, 89, 36, 49,
       63,  7, 99,  3, 82, 35, 78, 14, 93, 91, 99, 78, 13, 18, 76, 33, 35,
       10, 27, 89, 96, 13, 66, 69,  7,  8, 10, 80, 38, 67, 12, 79, 28, 93,
       29, 28, 90, 68, 55, 50, 48, 22, 31, 53, 18, 60, 21, 24, 81, 85, 79,
       32, 13,  9,  3, 76, 71, 15, 57, 12, 46, 35, 61,  4, 73, 96, 34, 81,
       11, 79, 71, 88,  6, 49, 97, 76, 13, 78,  2, 97, 10, 93, 22, 98, 14,
        0,  7, 98, 10, 67, 82, 72, 55,  1, 22, 18, 37, 17, 11,  4, 54, 87,
       71, 76, 39, 46,  5, 85, 15,  0, 91, 31,  5, 81, 69, 76, 58, 89, 23,
       53,  3, 40, 12,  5, 28,  6, 47, 15, 58,  8, 80, 15, 71, 21,  0, 62,
       42, 25, 55, 57, 68, 77, 83, 25, 68, 31,  8, 98, 81, 47, 50,  9, 73,
       58, 91, 70, 98,  6

In [6]:
y

array([58, 49, 88, 69, 44, 43,  7, 51, 33, 43, 33, 51, 55,  4, 60,  1, 46,
       74, 53, 48, 22, 69, 79, 34, 29, 35, 30, 47, 50, 56, 99, 78, 58, 43,
        0, 99, 85, 90, 77, 10, 85, 73,  4, 16, 24, 76, 85,  0, 13, 81, 68,
       21, 36, 13, 95, 34,  8,  1, 19,  2, 30, 45, 99, 61, 76, 80, 45, 32,
       14, 49,  1, 43, 83, 95, 97, 71, 17, 91, 93, 67, 47, 76, 12, 45, 20,
       51, 56, 92,  9, 41, 59, 33, 96, 70, 90, 83, 54,  6, 88, 78, 36, 51,
       99, 47, 47, 73,  6, 61, 78, 15,  1, 52, 26, 60,  0, 26, 32, 30, 97,
       45, 39, 77, 78, 69, 73,  8, 27, 35, 18, 15, 59,  5, 16, 19,  3, 33,
       37, 33, 81, 17, 43, 30, 40, 37, 51, 89, 79, 73, 35, 60, 22, 83, 38,
       44, 26,  3, 34, 39, 55, 65,  8, 31, 59, 91, 63, 85, 24, 71, 56, 91,
       25, 97, 61, 15, 15, 12, 41, 65, 61,  3, 35, 51, 72, 82, 58, 57, 39,
       34, 96, 72,  2, 56, 19, 21, 22, 22, 79, 68, 20, 82, 46, 39, 52, 21,
       83, 97,  4,  1, 87, 21, 73,  8, 10, 62, 39, 67,  2, 26, 24, 45, 64,
       63, 87, 11,  0, 37

In [7]:
z

array([57, 61, 76, 74, 77, 77, 56, 71, 14, 27, 20, 46,  7, 47, 63, 11, 90,
       65, 25, 99, 98, 53, 81, 33, 55, 96, 42,  6, 52, 69, 79, 24, 40, 81,
       26, 78, 93, 71,  2, 81, 39, 68,  4, 32, 47, 48, 76, 25, 82, 88, 85,
       68, 52, 53, 77, 93, 71, 95, 75, 39, 43, 68, 42, 18, 72, 17, 86, 94,
        1, 43,  9, 64, 21, 36, 18, 24, 38, 33, 32, 68, 94,  4, 34,  4, 28,
       76, 55, 38, 84, 16, 64, 97, 16,  6, 62, 91,  0, 11, 69,  7, 56, 79,
        4, 29, 66, 57, 10, 62, 19, 39, 18, 33, 53, 85, 74, 74, 86, 78, 41,
       86, 33, 50, 32, 92, 82, 53, 92,  1, 19, 36, 29, 87, 28, 57, 65, 38,
        9,  8, 15,  6, 55, 88, 99, 77, 48,  7, 20, 21, 18, 29, 37, 72, 27,
       96, 80, 37, 61, 47, 68, 87, 73, 56, 76, 72, 47, 83,  5,  9, 66, 18,
       68, 50, 47, 90, 74, 29, 78, 16, 86, 65, 32,  4, 90, 46, 22, 46, 27,
       71, 20, 90, 20, 82,  8,  1, 84, 13, 70, 56, 93, 25, 92,  7, 35, 76,
       63, 33, 35, 20, 27, 29, 98, 80, 64, 59, 51, 25, 19, 18, 54, 23, 13,
       63, 48, 37, 88,  1

In [8]:
out

array([43.17, 50.25, 60.78, 54.39, 57.57, 52.83, 31.59, 52.05, 18.48,
       26.7 , 23.88, 39.21, 21.72, 29.43, 54.18, 14.22, 57.48, 51.72,
       29.43, 64.71, 62.28, 45.48, 60.45, 33.63, 41.49, 61.77, 36.54,
       23.07, 43.83, 51.96, 72.96, 33.66, 35.67, 56.67, 21.63, 65.43,
       71.7 , 65.82, 23.01, 48.84, 42.81, 57.06,  6.42, 23.4 , 30.72,
       43.53, 59.97, 14.46, 48.  , 65.22, 68.13, 48.36, 41.37, 32.94,
       70.8 , 59.73, 42.72, 49.5 , 47.76, 25.32, 36.6 , 45.66, 46.26,
       32.55, 56.13, 35.88, 57.9 , 60.03,  9.54, 34.32, 13.74, 43.23,
       38.01, 44.31, 39.48, 30.54, 31.83, 46.86, 47.55, 57.78, 60.39,
       21.9 , 27.06, 15.81, 22.23, 51.9 , 43.92, 49.47, 53.64, 19.17,
       52.74, 63.6 , 31.83, 20.58, 54.12, 73.53, 16.38, 13.08, 57.39,
       29.4 , 39.72, 60.9 , 28.41, 28.59, 53.04, 52.71, 11.49, 50.76,
       32.73, 25.47, 12.21, 34.08, 34.89, 63.15, 39.63, 46.14, 58.83,
       54.63, 51.3 , 57.54, 27.36, 44.79, 35.31, 70.32, 65.73, 30.3 ,
       58.53,  9.99,

In [9]:
df = {"x" : normalize(x),
     "y" : normalize(y),
     "z" : normalize(z),
     "out" : normalize(out)}

In [10]:
df = pd.DataFrame(df)

In [11]:
df.to_csv("normalizedData.csv")