In [12]:
import numpy as np
import pandas as pd

In [47]:
data = pd.read_csv("data.csv")

In [48]:
data

Unnamed: 0   x   y   z    out
0             0   2  58  57  43.17
1             1  82  49  61  50.25
2             2  10  88  76  60.78
3             3   1  69  74  54.39
4             4  86  44  77  57.57
..          ...  ..  ..  ..    ...
995         995  61  97  17  37.44
996         996  31  29  68  44.43
997         997  63  33  62  45.21
998         998  40  88  40  45.12
999         999  78  17  21  21.81

[1000 rows x 5 columns]

In [49]:
data = data.iloc[:,1:]

In [50]:
data

x   y   z    out
0     2  58  57  43.17
1    82  49  61  50.25
2    10  88  76  60.78
3     1  69  74  54.39
4    86  44  77  57.57
..   ..  ..  ..    ...
995  61  97  17  37.44
996  31  29  68  44.43
997  63  33  62  45.21
998  40  88  40  45.12
999  78  17  21  21.81

[1000 rows x 4 columns]

In [51]:
inputData = data.iloc[:,:-1]
outputData = data.iloc[:,-1:]

In [52]:
datain = np.array(inputData)
dataout = np.array(outputData)

In [53]:
datain

array([[ 2, 58, 57],
       [82, 49, 61],
       [10, 88, 76],
       ...,
       [63, 33, 62],
       [40, 88, 40],
       [78, 17, 21]], dtype=int64)

In [54]:
dataout

array([[43.17],
       [50.25],
       [60.78],
       [54.39],
       [57.57],
       [52.83],
       [31.59],
       [52.05],
       [18.48],
       [26.7 ],
       [23.88],
       [39.21],
       [21.72],
       [29.43],
       [54.18],
       [14.22],
       [57.48],
       [51.72],
       [29.43],
       [64.71],
       [62.28],
       [45.48],
       [60.45],
       [33.63],
       [41.49],
       [61.77],
       [36.54],
       [23.07],
       [43.83],
       [51.96],
       [72.96],
       [33.66],
       [35.67],
       [56.67],
       [21.63],
       [65.43],
       [71.7 ],
       [65.82],
       [23.01],
       [48.84],
       [42.81],
       [57.06],
       [ 6.42],
       [23.4 ],
       [30.72],
       [43.53],
       [59.97],
       [14.46],
       [48.  ],
       [65.22],
       [68.13],
       [48.36],
       [41.37],
       [32.94],
       [70.8 ],
       [59.73],
       [42.72],
       [49.5 ],
       [47.76],
       [25.32],
       [36.6 ],
       [45.66],
       [

In [55]:
from keras.models import Sequential
from keras.layers import Dense
from sklearn.metrics import mean_squared_error

In [65]:
model = Sequential()
model.add(Dense(2, input_dim = 3, activation = 'linear'))
model.add(Dense(1, activation = 'linear'))

model.compile(loss = "mean_squared_error", optimizer = "adam")


In [66]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_8 (Dense)             (None, 2)                 8         
                                                                 
 dense_9 (Dense)             (None, 1)                 3         
                                                                 
Total params: 11
Trainable params: 11
Non-trainable params: 0
_________________________________________________________________


In [67]:
model.fit(datain, dataout, epochs = 500)

ypred = model.predict(datain)
mse = mean_squared_error(dataout, ypred)
print(mse)

Epoch 1/500
32/32 [==============================] - 0s 1ms/step - loss: 1981.1580
Epoch 2/500
32/32 [==============================] - 0s 1ms/step - loss: 1627.9819
Epoch 3/500
32/32 [==============================] - 0s 964us/step - loss: 1347.4623
Epoch 4/500
32/32 [==============================] - 0s 952us/step - loss: 1128.5675
Epoch 5/500
32/32 [==============================] - 0s 792us/step - loss: 952.9676
Epoch 6/500
32/32 [==============================] - 0s 1ms/step - loss: 806.4042
Epoch 7/500
32/32 [==============================] - 0s 1ms/step - loss: 689.8539
Epoch 8/500
32/32 [==============================] - 0s 868us/step - loss: 590.3881
Epoch 9/500
32/32 [==============================] - 0s 640us/step - loss: 506.7097
Epoch 10/500
32/32 [==============================] - 0s 973us/step - loss: 435.6418
Epoch 11/500
32/32 [==============================] - 0s 1ms/step - loss: 376.5008
Epoch 12/500
32/32 [==============================] - 0s 1ms/step - loss: 326.36

32/32 [==============================] - 0s 1ms/step - loss: 0.0258
Epoch 101/500
32/32 [==============================] - 0s 1ms/step - loss: 0.0256
Epoch 102/500
32/32 [==============================] - 0s 1ms/step - loss: 0.0254
Epoch 103/500
32/32 [==============================] - 0s 1ms/step - loss: 0.0251
Epoch 104/500
32/32 [==============================] - 0s 831us/step - loss: 0.0250
Epoch 105/500
32/32 [==============================] - 0s 1ms/step - loss: 0.0246
Epoch 106/500
32/32 [==============================] - 0s 872us/step - loss: 0.0244
Epoch 107/500
32/32 [==============================] - 0s 684us/step - loss: 0.0241
Epoch 108/500
32/32 [==============================] - 0s 1ms/step - loss: 0.0239
Epoch 109/500
32/32 [==============================] - 0s 713us/step - loss: 0.0237
Epoch 110/500
32/32 [==============================] - 0s 765us/step - loss: 0.0234
Epoch 111/500
32/32 [==============================] - 0s 1ms/step - loss: 0.0232
Epoch 112/500
32/32 

32/32 [==============================] - 0s 1ms/step - loss: 0.0030
Epoch 199/500
32/32 [==============================] - 0s 1ms/step - loss: 0.0029
Epoch 200/500
32/32 [==============================] - 0s 1ms/step - loss: 0.0028
Epoch 201/500
32/32 [==============================] - 0s 694us/step - loss: 0.0027
Epoch 202/500
32/32 [==============================] - 0s 1ms/step - loss: 0.0026
Epoch 203/500
32/32 [==============================] - 0s 1ms/step - loss: 0.0024
Epoch 204/500
32/32 [==============================] - 0s 898us/step - loss: 0.0023
Epoch 205/500
32/32 [==============================] - 0s 723us/step - loss: 0.0022
Epoch 206/500
32/32 [==============================] - 0s 1ms/step - loss: 0.0021
Epoch 207/500
32/32 [==============================] - 0s 787us/step - loss: 0.0020
Epoch 208/500
32/32 [==============================] - 0s 719us/step - loss: 0.0019
Epoch 209/500
32/32 [==============================] - 0s 649us/step - loss: 0.0018
Epoch 210/500
32/3

32/32 [==============================] - 0s 1ms/step - loss: 1.7202e-07
Epoch 294/500
32/32 [==============================] - 0s 708us/step - loss: 1.3611e-07
Epoch 295/500
32/32 [==============================] - 0s 807us/step - loss: 1.1482e-07
Epoch 296/500
32/32 [==============================] - 0s 672us/step - loss: 9.0989e-08
Epoch 297/500
32/32 [==============================] - 0s 974us/step - loss: 7.2179e-08
Epoch 298/500
32/32 [==============================] - 0s 772us/step - loss: 5.9973e-08
Epoch 299/500
32/32 [==============================] - 0s 696us/step - loss: 4.8521e-08
Epoch 300/500
32/32 [==============================] - 0s 1ms/step - loss: 3.7851e-08
Epoch 301/500
32/32 [==============================] - 0s 1ms/step - loss: 3.0819e-08
Epoch 302/500
32/32 [==============================] - 0s 991us/step - loss: 2.3583e-08
Epoch 303/500
32/32 [==============================] - 0s 1ms/step - loss: 2.0293e-08
Epoch 304/500
32/32 [==============================] -

32/32 [==============================] - 0s 930us/step - loss: 6.1118e-12
Epoch 387/500
32/32 [==============================] - 0s 785us/step - loss: 5.7416e-12
Epoch 388/500
32/32 [==============================] - 0s 668us/step - loss: 5.3294e-12
Epoch 389/500
32/32 [==============================] - 0s 931us/step - loss: 4.9865e-12
Epoch 390/500
32/32 [==============================] - 0s 3ms/step - loss: 5.8390e-12
Epoch 391/500
32/32 [==============================] - 0s 1ms/step - loss: 6.7203e-12
Epoch 392/500
32/32 [==============================] - 0s 1ms/step - loss: 6.7344e-12
Epoch 393/500
32/32 [==============================] - 0s 826us/step - loss: 7.6618e-12
Epoch 394/500
32/32 [==============================] - 0s 1ms/step - loss: 9.7371e-12
Epoch 395/500
32/32 [==============================] - 0s 1ms/step - loss: 6.0709e-12
Epoch 396/500
32/32 [==============================] - 0s 912us/step - loss: 6.9397e-12
Epoch 397/500
32/32 [==============================] - 0

32/32 [==============================] - 0s 856us/step - loss: 6.3669e-08
Epoch 481/500
32/32 [==============================] - 0s 798us/step - loss: 1.7034e-07
Epoch 482/500
32/32 [==============================] - 0s 815us/step - loss: 1.4781e-07
Epoch 483/500
32/32 [==============================] - 0s 741us/step - loss: 3.0437e-07
Epoch 484/500
32/32 [==============================] - 0s 698us/step - loss: 1.2423e-07
Epoch 485/500
32/32 [==============================] - 0s 770us/step - loss: 7.2773e-09
Epoch 486/500
32/32 [==============================] - 0s 1ms/step - loss: 1.2293e-08
Epoch 487/500
32/32 [==============================] - 0s 2ms/step - loss: 1.5679e-08
Epoch 488/500
32/32 [==============================] - 0s 3ms/step - loss: 1.1721e-07
Epoch 489/500
32/32 [==============================] - 0s 1ms/step - loss: 1.2081e-04
Epoch 490/500
32/32 [==============================] - 0s 1ms/step - loss: 1.4952e-05
Epoch 491/500
32/32 [==============================] - 0

In [68]:
help(Sequential.fit)

Help on function fit in module keras.engine.training:

fit(self, x=None, y=None, batch_size=None, epochs=1, verbose='auto', callbacks=None, validation_split=0.0, validation_data=None, shuffle=True, class_weight=None, sample_weight=None, initial_epoch=0, steps_per_epoch=None, validation_steps=None, validation_batch_size=None, validation_freq=1, max_queue_size=10, workers=1, use_multiprocessing=False)
    Trains the model for a fixed number of epochs (iterations on a dataset).
    
    Args:
        x: Input data. It could be:
          - A Numpy array (or array-like), or a list of arrays
            (in case the model has multiple inputs).
          - A TensorFlow tensor, or a list of tensors
            (in case the model has multiple inputs).
          - A dict mapping input names to the corresponding array/tensors,
            if the model has named inputs.
          - A `tf.data` dataset. Should return a tuple
            of either `(inputs, targets)` or
            `(inputs, target

In [ ]:
l1_n1_w1 = 0.3
l1_n1_w2 = 0.6
l1_n1_w3 = -0.3

l1_n2_w1 = 0.2
l1_n2_w2 = 0.5
l1_n2_w3 = 0.8

l2_n1_w1 = -0.1
l2_n1_w2 = 0.6

In [61]:
model.weights

[<tf.Variable 'dense_6/kernel:0' shape=(3, 2) dtype=float32, numpy=
 array([[ 0.03701732, -1.1642718 ],
        [-0.4087736 , -0.45224056],
        [-0.31375712,  0.00475956]], dtype=float32)>,
 <tf.Variable 'dense_6/bias:0' shape=(2,) dtype=float32, numpy=array([-0.63670546, -0.22260697], dtype=float32)>,
 <tf.Variable 'dense_7/kernel:0' shape=(2, 1) dtype=float32, numpy=
 array([[-0.90543824],
        [-1.0433702 ]], dtype=float32)>,
 <tf.Variable 'dense_7/bias:0' shape=(1,) dtype=float32, numpy=array([41.161903], dtype=float32)>]

In [64]:
model.predict([[12,15,10]])

1/1 [==============================] - 0s 21ms/step


array([[41.161903]], dtype=float32)